COIN = Dimecoin
DB_DIRECTORY = /var/electrumx/db
DAEMON_URL = http://user:password@host.docker.internal:8332/
PEER_DISCOVERY = on
HOST = 0.0.0.0
TCP_PORT = 10061
SSL_PORT = 20061
RPC_PORT = 8000
WS_PORT = 30061
BANNER_FILE = /var/electrumx/banner
