name: 'Build & Check Dime Protocol(x86_64-linux-gnu): No QT'

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        os: [x86_64-linux-gnu]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Get Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential \
            libtool \
            autotools-dev \
            automake \
            pkg-config \
            libssl-dev \
            libevent-dev \
            bsdmainutils \
            python3 \
            libboost-system-dev \
            libboost-filesystem-dev \
            libboost-chrono-dev \
            libboost-test-dev \
            libboost-thread-dev \
            libboost-dev \
            libsqlite3-dev \
            libqt5gui5 \
            libqt5core5a \
            libqt5dbus5 \
            qttools5-dev \
            qttools5-dev-tools \
            libqrencode-dev \
            software-properties-common \
            pandoc

      - name: Install BerkeleyDB
        run: ./contrib/install_db4.sh "$(pwd)" --enable-cxx

      - name: Auto Generate
        run: ./autogen.sh

      - name: Configure
        run: |
          export BDB_PREFIX="${PWD}/db4"

          ./configure \
            BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" \
            BDB_CFLAGS="-I${BDB_PREFIX}/include" \
            --without-gui

      - name: Make
        run: make -j4

      - name: Run unit tests
        run: |
          if ! make check; then
            echo "=== secp256k1 tests.log ==="
            cat src/secp256k1/tests.log || true

            echo "=== secp256k1 test-suite.log ==="
            cat src/secp256k1/test-suite.log || true

            echo "=== other failed test logs ==="
            find . -name '*.log' -type f -print -exec cat {} \; || true

            exit 1
          fi

      - name: Upload Test Suite Logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-suite-logs
          path: |
            src/test-suite.log
            src/**/*.log
            **/test-suite.log
            **/tests.log
          if-no-files-found: ignore

